// apps/client/src/lib/components/ui/content/WorkCard.svelte
<script lang="ts">
    import type { Content } from '$lib/models/content';
    import { ContentKind } from '$lib/models/content';
    import { TagKind } from '$lib/models/content/works';
    import { abbreviate, localeDate } from '$lib/util';
    import { CardSize } from '$lib/models/site';
    import TagBadge from './TagBadge.svelte';
    import {
        ArrowDownSLine,
        ArrowUpSLine,
        Calendar2Line,
        DiscussLine,
        HeartLine,
        MoreLine,
        PenNibLine,
        RhythmFill,
    } from 'svelte-remixicon';

    export let content: Content;
    export let size: CardSize = CardSize.Medium;
    export let showAllTags = false;

    let contentUrl = `/prose`;

    const calculateApprovalRating = (likes: number, dislikes: number): number => {
        const totalVotes = likes + dislikes;
        if (totalVotes === 0) {
            return 0;
        } else {
            return Math.ceil((likes / totalVotes) * 100);
        }
    };

    function toggle() {
        showAllTags = !showAllTags;
    }
</script>

<span
    class="card border border-gray-600 dark:border-white group hover:bg-gray-100 hover:dark:bg-zinc-700"
>
    <div class="flex flex-wrap items-center">
        <h3 class="title" title={content.title}>
            <a href={content.kind === ContentKind.ProseContent ? `/prose/${content._id}` : contentUrl = `/poetry/${content._id}`}>
                {content.title}
            </a>
        </h3>
        <TagBadge kind={TagKind.Rating} rating={content.meta.rating} hasIcon={false} />
    </div>
    <div
        class="flex flex-wrap items-center pb-0.5 pt-0.5 text-xs border-b border-gray-600 dark:border-white group-active:border-white"
    >
        <div class="author flex-1" title="by {content.author.screenName}">
            <a href="/profile/{content.author._id}">
                by {content.author.screenName}
            </a>
        </div>
        <div class="flex items-center" title="Approval rating">
            <HeartLine size="16px" />
            <span>{calculateApprovalRating(content.stats.likes, content.stats.dislikes)}%</span>
        </div>
    </div>
    <div class="flex items-center flex-wrap mb-2">
        <TagBadge kind={TagKind.Type} type={content.kind} size={'medium'} />
        <TagBadge kind={TagKind.Category} category={content.meta.category} size={'medium'} />
        {#each content.meta.genres as genre}
            <TagBadge kind={TagKind.Genre} {genre} size={'medium'} />
        {/each}
    </div>
    <div class="flex items-center flex-wrap mb-2">
        {#if showAllTags}
            {#each content.tags as tag}
                <TagBadge kind={TagKind.Fandom} {tag} size={'medium'} />
            {/each}
            {#if content.tags.length > 1}
                <div class="flex mx-0.5 mt-1" on:click={toggle} title="Less">
                    <ArrowUpSLine/>
                </div>
            {/if}
        {:else}
            {#if content.tags.length > 0}
                <TagBadge kind={TagKind.Fandom} tag={content.tags[0]} size={'medium'} />
            {/if}
            {#if content.tags.length > 1}
                <div class="flex mx-0.5 mt-1" on:click={toggle} title="More">
                    <MoreLine/>
                    <ArrowDownSLine/>
                </div>
            {/if}
        {/if}
    </div>
    <div class="work-body">
        {#if content.meta.coverArt}
            <div class="cover">
                <img src={content.meta.coverArt} alt="cover" />
            </div>
        {/if}
        <div class="desc">
            {content.desc}
        </div>
    </div>
    <div class="work-meta bg-gray-200 dark:bg-gray-600">
        <div class="flex items-center" title="{content.stats.views} views">
            <RhythmFill size="16px" />
            <span>{abbreviate(content.stats.views)}</span>
        </div>
        <div class="text-sm mx-0.5 relative -top-0.5">•</div>
        <div class="flex items-center" title="{content.stats.words} words">
            <PenNibLine size="16px" />
            <span>{abbreviate(content.stats.words)}</span>
        </div>
        <div class="text-sm mx-0.5 relative -top-0.5">•</div>
        <div class="flex items-center" title="{content.stats.comments} comments">
            <DiscussLine size="16px" />
            <span>{abbreviate(content.stats.comments)}</span>
        </div>
        <div class="text-sm mx-0.5 relative -top-0.5">•</div>
        <div>
            {content.meta.status}
        </div>
        <div class="flex-1" />
        <div class="flex items-center" title="Published on">
            <Calendar2Line size="16px" />
            <span>
                {#if content.audit.publishedOn}
                    {localeDate(content.audit.publishedOn, 'shortDate')}
                {:else}
                    {localeDate(content.createdAt, 'shortDate')}
                {/if}
            </span>
        </div>
    </div>
</span>

<style lang="scss">
    span.card {
        @apply block flex flex-col p-2 transition transform select-none cursor-pointer h-full rounded-md;
        color: var(--text-color);
        h3.title {
            @apply relative top-0.5 font-medium flex-1 text-xl overflow-hidden overflow-ellipsis whitespace-nowrap;
        }
        &:hover {
            @apply scale-105 no-underline z-30;
            box-shadow: var(--dropshadow);
            div.work-meta {
                @apply bg-gray-300;
            }
        }
        div.author {
            a {
                color: var(--text-color);
            }
        }
        div.work-body {
            @apply flex-1 mb-2;
            div.cover {
                @apply mr-2;
                img {
                    @apply object-contain rounded-lg float-left mr-2 mb-0.5;
                    max-width: 6.5rem;
                    max-height: 6.5rem;
                }
            }
            div.desc {
                @apply text-sm;
            }
        }
        div.work-meta {
            @apply rounded-md px-1 text-xs flex items-center;
            :global(svg) {
                @apply mr-0.5;
            }
        }
        &:active {
            @apply scale-100 text-white;
            background: var(--accent);
            h3.title {
                color: white !important;
            }
            div.work-meta {
                background: var(--accent-light);
            }
        }
        &.active {
            @apply scale-105 text-white bg-gray-100;
            box-shadow: var(--dropshadow);
            h3.title {
                @apply text-white;
            }
            div.work-meta {
                @apply bg-gray-300;
            }
        }
    }
</style>

// libs/client/ui/src/lib/components/work-card/work-card.component.ts
import { Component, Input } from '@angular/core';
import { ContentKind, Genres, TagKind } from '@dragonfish/shared/models/content';

import { calculateApprovalRating } from '@dragonfish/shared/functions';
import { slugify } from 'voca';

@Component({
    selector: 'dragonfish-work-card',
    templateUrl: './work-card.component.html',
    styleUrls: ['./work-card.component.scss'],
})
export class WorkCardComponent {
    @Input() content;
    @Input() showAuthor: boolean;
    @Input() size: 'small' | 'large' = 'large';

    contentKind = ContentKind;
    contentGenres = Genres;
    tagKind = TagKind;

    showAllTags = false;

    calcApprovalRating(likes: number, dislikes: number) {
        return calculateApprovalRating(likes, dislikes);
    }

    toggleShowAllTags() {
        this.showAllTags = !this.showAllTags;
    }

    createContentUrl(kind: ContentKind, id: string, title: string) {
        if (kind === ContentKind.ProseContent) {
            return ['/prose', id, slugify(title)];
        } else if (kind === ContentKind.PoetryContent) {
            return ['/poetry', id, slugify(title)];
        }
    }
}

<span class="medium-card border border-gray-600 dark:border-white group" *ngIf="size === 'large'">
    <div class="flex items-center">
        <h3
            class="title"
            [matTooltip]="content.title"
            [matTooltipClass]="'offprint-tooltip'"
            [matTooltipShowDelay]="600"
        >
            <a
                class="title-link"
                [routerLink]="createContentUrl(content.kind, content._id, content.title)"
            >
                {{ content.title }}
            </a>
        </h3>
        <dragonfish-tag-badge [kind]="tagKind.Rating" [rating]="content.meta.rating" [hasIcon]="false"></dragonfish-tag-badge>
    </div>
    <div class="flex items-center pb-0.5 text-xs border-b border-gray-600 dark:border-white group-hover:border-white">
        <div class="flex-1">
            by 
            <a
                class="author-link"
                [routerLink]="['/profile', content.author._id, content.author.userTag]"
            >
                {{ $any(content.author).screenName }}
            </a>
        </div>
        <div class="flex items-center">
            <rmx-icon name="heart-line" class="relative top-1" style="width: 1rem;"></rmx-icon>
            <span>{{ calcApprovalRating(content.stats.likes, content.stats.dislikes) }}%</span>
        </div>
    </div>
    <div class="flex items-center flex-wrap mb-2">
        <dragonfish-tag-badge [kind]="tagKind.Type" [type]="content.kind" [size]="'medium'"></dragonfish-tag-badge>
        <dragonfish-tag-badge [kind]="tagKind.Category" [category]="content.meta.category" [size]="'medium'"></dragonfish-tag-badge>
        <ng-container *ngFor="let genre of content.meta.genres">
            <dragonfish-tag-badge [kind]="tagKind.Genre" [genre]="genre" [size]="'medium'"></dragonfish-tag-badge>
        </ng-container>
    </div>
    <ng-container *ngIf="content.tags !== null && content.tags.length > 0">
        <div class="card-tags flex flex-wrap items-center">
            <ng-container *ngIf="content.tags.length === 1; else multipleTags">
                    <a
                        class="tags"
                        [routerLink]="['/tag', content.tags[0]._id, content.tags[0].name | slugify]"
                        [innerHtml]="content.tags[0] | displayTags | safeHtml"
                    ></a>
            </ng-container>
            <ng-template #multipleTags>
                <ng-container *ngIf="showAllTags; else showOneTag">
                        <ng-container *ngFor="let tag of content.tags; let i = index">
                            <a
                                class="tags"
                                [routerLink]="['/tag', tag._id, tag.name | slugify]"
                                [innerHtml]="tag | displayTags | safeHtml"
                            ></a>
                            <ng-container *ngIf="i < content.tags.length - 1">
                                ,&nbsp;
                            </ng-container>
                        </ng-container>
                    <rmx-icon name="arrow-up-s-line" (click)="toggleShowAllTags()"></rmx-icon>
                </ng-container>
                <ng-template #showOneTag>
                        <a
                            class="tags"
                            [routerLink]="['/tag', content.tags[0]._id, content.tags[0].name | slugify]"
                            [innerHtml]="content.tags[0] | displayTags | safeHtml"
                        ></a>
                    <rmx-icon name="arrow-down-s-line" (click)="toggleShowAllTags()"></rmx-icon>
                </ng-template>
            </ng-template>
        </div>
    </ng-container>
    <div class="work-body">
        <div class="cover" *ngIf="$any(content.meta).coverArt">
            <img [src]="$any(content.meta).coverArt" [alt]="'cover'">
        </div>
        <div class="desc">
            {{ content.desc }}
        </div>
    </div>
    <div class="work-meta bg-gray-200 dark:bg-gray-600">
        <div class="flex items-center" [matTooltip]="'Views'" [matTooltipClass]="'offprint-tooltip'" [matTooltipShowDelay]="300">
            <rmx-icon name="rhythm-fill" class="relative top-1 mr-0.5" style="width: 1rem;"></rmx-icon>
            <span>{{ content.stats.views | abbreviate }}</span>
        </div>
        <div class="text-sm mx-0.5 relative -top-0.5">
            •
        </div>
        <div class="flex items-center" [matTooltip]="'Words'" [matTooltipClass]="'offprint-tooltip'" [matTooltipShowDelay]="300">
            <rmx-icon name="pen-nib-line" class="relative top-1 mr-0.5" style="width: 1rem;"></rmx-icon>
            <span>{{ content.stats.words | abbreviate }}</span>
        </div>
        <div class="text-sm mx-0.5 relative -top-0.5">
            •
        </div>
        <div class="flex items-center" [matTooltip]="'Comments'" [matTooltipClass]="'offprint-tooltip'" [matTooltipShowDelay]="300">
            <rmx-icon name="discuss-line" class="relative top-1 mr-0.5" style="width: 1rem;"></rmx-icon>
            <span>{{ content.stats.comments | abbreviate }}</span>
        </div>
        <div class="text-sm mx-0.5 relative -top-0.5">
            •
        </div>
        <ng-container *ngIf="content.audit.publishedOn; else creationDate">
            <div class="flex items-center" [matTooltip]="'Published on'" [matTooltipClass]="'offprint-tooltip'" [matTooltipShowDelay]="300">
                <rmx-icon name="calendar-2-line" class="relative top-1 mr-0.5" style="width: 1rem;"></rmx-icon>
                <span>{{ content.audit.publishedOn | localedate: 'shortDate' }}</span>
            </div>
        </ng-container>
        <ng-template #creationDate>
            <div class="flex items-center" [matTooltip]="'Created on'" [matTooltipClass]="'offprint-tooltip'" [matTooltipShowDelay]="300">
                <rmx-icon name="calendar-2-line" class="relative top-1 mr-0.5" style="width: 1rem;"></rmx-icon>
                <span>{{ content.createdAt | localedate: 'shortDate' }}</span>
            </div>
        </ng-template>
        <div class="flex-1"></div>
        <div>
            {{ content.meta.status }}
        </div>
    </div>
</span>

<span
    class="small-card block group flex flex-col p-2 transition transform select-none cursor-pointer border border-gray-600 dark:border-white rounded-md hover:scale-105 hover:text-white hover:no-underline hover:z-30"
    *ngIf="size === 'small'"
    [ngClass]="{'active': isActive, 'h-full': fullHeight}"
>
    <div class="flex">
        <h4
            class="block align-top text-lg font-medium overflow-ellipsis overflow-hidden whitespace-nowrap flex-1 self-center group-hover:text-white"
            style="line-height: 2rem;"
            [matTooltip]="content.title"
            [matTooltipClass]="'offprint-tooltip'"
            [matTooltipShowDelay]="300"
            [routerLink]="createContentUrl(content.kind, content._id, content.title)"
        >
            <a
                class="title-link"
                [routerLink]="createContentUrl(content.kind, content._id, content.title)"
            >
                {{ content.title }}
            </a>
        </h4>
        <dragonfish-tag-badge [kind]="tagKind.Rating" [rating]="content.meta.rating" [size]="'small'" [hasIcon]="false"></dragonfish-tag-badge>
    </div>
    <div class="flex items-center flex-wrap mb-2">
        <dragonfish-tag-badge [kind]="tagKind.Type" [type]="content.kind" [size]="size"></dragonfish-tag-badge>
        <dragonfish-tag-badge [kind]="tagKind.Category" [category]="content.meta.category" [size]="size"></dragonfish-tag-badge>
        <ng-container *ngFor="let genre of content.meta.genres">
            <dragonfish-tag-badge [kind]="tagKind.Genre" [genre]="genre" [size]="size"></dragonfish-tag-badge>
        </ng-container>
    </div>
    <div class="flex-1 mb-2">
        <div class="mr-2" *ngIf="$any(content.meta).coverArt">
            <img [src]="$any(content.meta).coverArt" [alt]="'cover'" class="object-contain rounded-lg float-left mr-2 mb-0.5" style="max-width: 5rem;">
        </div>
        <div class="text-sm line-clamp-4">
            {{ content.desc }}
        </div>
    </div>
    <div class="rounded-md px-1 text-xs flex items-center bg-gray-200 dark:bg-gray-600">
        <div>
            by 
            <a
                class="author-link"
                [routerLink]="['/profile', content.author._id, content.author.userTag]"
            >
                {{ $any(content.author).screenName }}
            </a>
        </div>
        <div class="text-sm mx-0.5 relative -top-0.5">
            •
        </div>
        <div>
            {{ content.stats.words | abbreviate }} word{{ content.stats.words | pluralize }}
        </div>
        <div class="flex-1"></div>
        <div class="flex items-center">
            <rmx-icon name="heart-line" class="relative top-1" style="width: 1rem;"></rmx-icon>
            <span>{{ calcApprovalRating(content.stats.likes, content.stats.dislikes) }}%</span>
        </div>
    </div>
</span>
