// apps/client/src/routes/dashboard/approval-queue/index.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { slugify, abbreviate, localeDate } from '$lib/util';
    import { approvalQueue, setCurrItem, claimItem } from '$lib/repo/approval-queue.repo';
    import { session } from '$lib/repo/session.repo';
    import { CheckLine, CloseLine, Loader5Line } from 'svelte-remixicon';
    import { setQueue } from '$lib/repo/approval-queue.repo';
    import TagBadge from '$lib/components/ui/content/TagBadge.svelte';
    import { TagKind } from '$lib/models/content/works';
    import type { Content } from '$lib/models/content';
    import { ContentKind } from '$lib/models/content';

    function openItem(docId: string, content: Content) {
        setCurrItem(docId);
        if (content.kind === ContentKind.ProseContent) {
            goto(`/prose/${content._id}/${slugify(content.title)}`);
        } else if (content.kind === ContentKind.PoetryContent) {
            goto(`/poetry/${content._id}/${slugify(content.title)}`);
        }
    }
</script>

{#if $session.account && $session.currProfile}
    {#await setQueue($session.currProfile._id)}
        <div class="flex flex-col items-center justify-center h-96 w-full">
            <div class="flex items-center">
                <Loader5Line class="animate-spin mr-2" size="32px" />
                <span class="uppercase font-bold tracking-widest">Loading queue...</span>
            </div>
        </div>
    {:then items}
        {#if $approvalQueue.queue.length === 0}
            <div class="flex flex-col items-center justify-center h-96 w-full">
                <div class="flex items-center">
                    <CheckLine class="mr-2" size="32px" />
                    <span class="uppercase font-bold tracking-widest">The queue is clear!</span>
                </div>
            </div>
        {:else}
            <div class="w-11/12 mx-auto md:max-w-7xl">
                <table class="table-auto my-6 border-collapse">
                    <thead class="border-b border-zinc-700 dark:border-white">
                        <tr>
                            <th>Claims</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Desc</th>
                            <th>Tags</th>
                            <!--<th>Fandom Tags</th>-->
                            <th>Rating</th>
                            <th>Words</th>
                            <th>Submitted</th>
                        </tr>
                    </thead>
                    <tbody>
                        {#each $approvalQueue.queue as item}
                            <tr class="border-b border-zinc-700 dark:border-white">
                                <td class="p-2 border-r border-zinc-700 dark:border-white">
                                    {#if item.claimedBy && item.claimedBy._id === $session.currProfile._id}
                                        <button
                                            on:click={() => openItem(item._id, item.workToApprove)}
                                            >View >></button
                                        >
                                    {:else if item.claimedBy && item.claimedBy._id !== $session.currProfile._id}
                                        <img
                                            class="w-12 h-12 rounded-md border border-gray-600 dark:border-white"
                                            src={item.claimedBy.profile.avatar}
                                            alt="avatar"
                                        />
                                    {:else}
                                        <button
                                            on:click={() =>
                                                claimItem($session.currProfile._id, item._id)}
                                            >Claim</button
                                        >
                                    {/if}
                                </td>
                                <td class="p-2 border-r border-gray-600 dark:border-white">
                                    {item.workToApprove.title}
                                </td>
                                <td class="p-2 border-r border-gray-600 dark:border-white">
                                    <a href="/profile/{item.workToApprove.author._id}">
                                        {item.workToApprove.author.screenName}
                                    </a>
                                </td>
                                <td class="p-2 border-r border-gray-600 dark:border-white">
                                    <button>View >></button>
                                </td>
                                <td
                                    class="p-2 flex items-center flex-wrap border-r border-gray-600 dark:border-white"
                                >
                                    <TagBadge
                                        kind={TagKind.Type}
                                        type={item.workToApprove.kind}
                                        size={'large'}
                                    />
                                    <TagBadge
                                        kind={TagKind.Category}
                                        category={item.workToApprove.meta.category}
                                        size={'large'}
                                    />
                                    {#each item.workToApprove.meta.genres as genre}
                                        <TagBadge kind={TagKind.Genre} {genre} size={'large'} />
                                    {/each}
                                </td>
                                <!--<td class="p-2 flex-wrap border-r border-gray-600 dark:border-white">
                                    {#each item.workToApprove.tags as tag}
                                    <ng-container *ngFor="let tag of entry.workToApprove.tags; let i = index">
                                        <a
                                            [routerLink]="['/tag', tag._id, tag.name | slugify]"
                                            [innerHtml]="tag | displayTags | safeHtml"
                                        ></a>
                                        <ng-container *ngIf="i < entry.workToApprove.tags.length - 1">
                                            ,
                                        </ng-container>
                                    </ng-container>
                                </td>-->
                                <td class="p-2 border-r border-gray-600 dark:border-white">
                                    {item.workToApprove.meta.rating}
                                </td>
                                <td class="p-2 border-r border-gray-600 dark:border-white">
                                    {abbreviate(item.workToApprove.stats.words)}
                                </td>
                                <td class="p-2">
                                    {localeDate(item.workToApprove.createdAt, 'shortDate')}
                                </td>
                            </tr>
                        {/each}
                    </tbody>
                </table>
            </div>
        {/if}
    {:catch error}
        <div class="flex flex-col items-center justify-center h-96 w-full">
            <div class="flex items-center">
                <CloseLine class="mr-2" size="32px" />
                <span class="uppercase font-bold tracking-widest">An error has occurred!</span>
            </div>
        </div>
    {/await}
{:else}
    <div class="flex flex-col items-center justify-center h-96 w-full">
        <div class="flex items-center">
            <CloseLine class="mr-2" size="32px" />
            <span class="uppercase font-bold tracking-widest"
                >Please select a profile before viewing this page</span
            >
        </div>
    </div>
{/if}

// libs/client/dashboard/src/lib/pages/approval-queue/approval-queue.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SessionQuery } from '@dragonfish/client/repository/session';
import { ApprovalQueue } from '@dragonfish/shared/models/approval-queue';
import { ContentKind, ContentModel, TagKind } from '@dragonfish/shared/models/content';
import { PaginateResult } from '@dragonfish/shared/models/util';
import { ApprovalQueueService } from '@dragonfish/client/repository/dashboard/approval-queue';
import { AlertsService } from '@dragonfish/client/alerts';
import { Pseudonym } from '@dragonfish/shared/models/accounts';
import { AuthService } from '@dragonfish/client/repository/session/services';

@Component({
    selector: 'dragonfish-approval-queue',
    templateUrl: './approval-queue.component.html',
    styleUrls: ['./approval-queue.component.scss'],
})
export class ApprovalQueueComponent implements OnInit {
    queue: PaginateResult<ApprovalQueue>;
    contentKind = ContentKind;
    tagKinds = TagKind;
    pageNum = 1;

    constructor(
        public route: ActivatedRoute,
        private router: Router,
        private alerts: AlertsService,
        public sessionQuery: SessionQuery,
        private queueService: ApprovalQueueService,
        private auth: AuthService,
    ) {}

    ngOnInit(): void {
        this.route.data.subscribe((data) => {
            this.queue = data.queueData as PaginateResult<ApprovalQueue>;
        });
    }

    /**
     * Handles page changing
     *
     * @param event The new page
     */
    onPageChange(event: number) {
        this.router.navigate([], {
            relativeTo: this.route,
            queryParams: { page: event },
            queryParamsHandling: 'merge',
        });
        this.pageNum = event;
    }

    /**
     * Goes to the appropriate content view for the following queue entry.
     *
     * @param entry The approval queue entry
     */
    goToContentView(entry: ApprovalQueue) {
        this.queueService.selectWork(entry);
        const content: ContentModel = entry.workToApprove as ContentModel;
        if (content.kind === ContentKind.ProseContent) {
            this.router.navigate(['view-prose'], { relativeTo: this.route });
        } else if (content.kind === ContentKind.PoetryContent) {
            this.router.navigate(['view-poetry'], { relativeTo: this.route });
        } else {
            this.alerts.warn(`...what's this doing here?`);
        }
    }

    /**
     * Forces a refresh of the current page of the queue.
     */
    forceRefresh() {
        // eventually, none of this will be necessary and items will be updated in-place.
        this.router.navigate([], {
            relativeTo: this.route,
            queryParams: { page: this.pageNum },
            queryParamsHandling: 'merge',
        });
    }

    /**
     * Checks to see if the queue is empty.
     */
    queueIsEmpty() {
        return this.queue.docs.length === 0;
    }

    /**
     * Checks to see if this entry has been claimed by anyone.
     *
     * @param entry The approval queue entry
     */
    checkIfClaimed(entry: ApprovalQueue) {
        return !(entry.claimedBy === null || entry.claimedBy === undefined);
    }

    /**
     * Checks to see if the provided entry is claimed by the currently signed in user.
     *
     * @param entry The approval queue entry
     */
    checkIfClaimedByThisUser(entry: ApprovalQueue) {
        if (entry.claimedBy !== null && entry.claimedBy !== undefined) {
            const whoClaimedThis = entry.claimedBy as Pseudonym;
            return this.auth.checkPseudonym(whoClaimedThis._id);
        } else {
            return false;
        }
    }

    /**
     * Claims an entry to the queue.
     *
     * @param entry The approval queue entry
     */
    claimWork(entry: ApprovalQueue) {
        this.queueService.claimWork(entry).subscribe(() => {
            this.forceRefresh();
        });
    }
}

<ng-container *ngIf="route.children.length === 0; else navigated">
    <ng-container *ngIf="queueIsEmpty(); else notEmpty">
        <div class="empty">
            <h3>Queue's clear!</h3>
            <p>If that was you, well done! If it wasn't, then just sit around and wait for more I guess.</p>
        </div>
    </ng-container>

    <ng-template #notEmpty>
        <table class="table-auto my-6 w-11/12 mx-auto border-collapse">
            <thead class="border-b border-gray-600 dark:border-white">
            <tr>
                <th>Claims</th>
                <th>Title</th>
                <th>Author</th>
                <th>Tags</th>
                <th>Rating</th>
                <th>Submitted</th>
            </tr>
            </thead>
            <tbody>
            <tr
                class="border-b border-gray-600 dark:border-white"
                *ngFor="let entry of queue.docs | paginate: { itemsPerPage: queue.limit, currentPage: pageNum, totalItems: queue.totalDocs }"
            >
                <td class="p-2 border-r border-gray-600 dark:border-white">
                    <ng-container *ngIf="checkIfClaimed(entry); else notClaimed">
                        <ng-container *ngIf="checkIfClaimedByThisUser(entry); else notThisUser">
                            <a>View >></a>
                        </ng-container>
                        <ng-template #notThisUser>
                            <img class="w-12 h-12 rounded-md border border-gray-600 dark:border-white" [src]="entry.claimedBy.profile.avatar" [alt]="'avatar'">
                        </ng-template>
                    </ng-container>
                    <ng-template #notClaimed>
                        <button (click)="claimWork(entry)">
                            <rmx-icon name="add-box-line"></rmx-icon>
                            <span>Claim</span>
                        </button>
                    </ng-template>
                </td>
                <td class="p-2 border-r border-gray-600 dark:border-white">
                    {{ entry.workToApprove.title }}
                </td>
                <td class="p-2 border-r border-gray-600 dark:border-white">
                    <a [routerLink]="['/profile', entry.workToApprove.author._id, entry.workToApprove.author.userTag]">
                        {{ entry.workToApprove.author.screenName }}
                    </a>
                </td>
                <td class="p-2 flex items-center flex-wrap border-r border-gray-600 dark:border-white">
                    <dragonfish-tag-badge [kind]="tagKinds.Type" [type]="entry.workToApprove.kind"></dragonfish-tag-badge>
                    <dragonfish-tag-badge [kind]="tagKinds.Category" [category]="entry.workToApprove.meta.category"></dragonfish-tag-badge>
                    <ng-container *ngFor="let genre of entry.workToApprove.meta.genres">
                        <dragonfish-tag-badge [kind]="tagKinds.Genre" [genre]="genre"></dragonfish-tag-badge>
                    </ng-container>
                </td>
                <td class="p-2 border-r border-gray-600 dark:border-white">
                    {{ entry.workToApprove.meta.rating }}
                </td>
                <td class="p-2">
                    {{ entry.createdAt | localedate: 'shortDate' }}
                </td>
            </tr>
            </tbody>
        </table>

        <pagination-controls
            (pageChange)="onPageChange($event)"
            previousLabel=""
            nextLabel=""
            *ngIf="!queueIsEmpty()"
        ></pagination-controls>
    </ng-template>
</ng-container>

<ng-template #navigated>
    <router-outlet></router-outlet>
</ng-template>
