// apps/client/src/lib/components/ui/content/BlogCard.svelte
<script lang="ts">
    import type { Blog } from '$lib/models/content/blogs';
    import { abbreviate, localeDate } from '$lib/util';
    import Avatar from '$lib/components/ui/user/Avatar.svelte';
    import { DiscussLine, BarChartBoxLine } from 'svelte-remixicon';
    import type { Content } from '$lib/models/content';

    export let blog: Blog | Content;
</script>

<a
    class="blog-card border-zinc-700 dark:border-white hover:bg-zinc-200 dark:hover:bg-zinc-700"
    href="/blog/{blog._id}"
>
    <div class="flex items-center p-4">
        <Avatar size="4rem" src={blog.author.profile.avatar} />
        <div class="ml-4 w-full">
            <h3 class="font-medium text-3xl">{blog.title}</h3>
            <div class="flex items-center w-full text-sm">
                <span class="flex-1 uppercase font-bold tracking-wider">
                    {localeDate(blog.createdAt, 'fullDate')}
                </span>
                <span class="flex items-center"
                    ><BarChartBoxLine class="mr-1" /> {abbreviate(blog.stats.views)}</span
                >
                <span class="mx-0.5">|</span>
                <span class="flex items-center"
                    ><DiscussLine class="mr-1" /> {abbreviate(blog.stats.comments)}</span
                >
            </div>
        </div>
    </div>
    <div class="blog-body px-4">
        {@html blog.body}
    </div>
    <div class="continue-reading" />
</a>

<style lang="scss">
    a.blog-card {
        @apply block w-full border rounded-lg h-72 relative no-underline transition transform overflow-hidden;
        color: var(--text-color);
        &:hover {
            @apply scale-105;
        }
        &:active {
            @apply scale-100;
        }
        div.continue-reading {
            @apply absolute z-10 bottom-0 w-full rounded-b-lg flex items-center justify-center h-12;
            background: linear-gradient(
                to top,
                var(--background),
                var(--background) calc(100% - 50px),
                rgba(0, 0, 0, 0) calc(100% - 5px),
                rgba(0, 0, 0, 0)
            );
        }
    }
</style>

// libs/client/ui/src/lib/components/blog-card/blog-card.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { BlogsContentModel, ContentKind } from '@dragonfish/shared/models/content';

@Component({
    selector: 'dragonfish-blog-card',
    templateUrl: './blog-card.component.html',
    styleUrls: ['./blog-card.component.scss'],
})
export class BlogCardComponent {
    @Input() blog: BlogsContentModel;
    @Input() showAuthor: boolean;
    @Input() showEditMenu = false;

    @Output() toPublish = new EventEmitter<BlogsContentModel>();
    @Output() toUnpublish = new EventEmitter<BlogsContentModel>();
    @Output() toDelete = new EventEmitter<string>();

    contentKind = ContentKind;
    editMenuOpened = false;

    toggleMenu() {
        this.editMenuOpened = !this.editMenuOpened;
    }

    publishBlog() {
        this.toPublish.emit(this.blog);
    }

    unpublishBlog() {
        this.toUnpublish.emit(this.blog);
    }

    deleteBlog() {
        this.toDelete.emit(this.blog._id);
    }
}

<div class="w-full my-2 h-72 relative flex flex-col rounded-md shadow-xl border border-gray-600 dark:border-white">
    <button
        class="absolute right-0.5 top-0.5"
        [ngClass]="{'active': editMenuOpened}"
        *ngIf="showEditMenu"
        [matMenuTriggerFor]="editingMenu"
        (menuOpened)="toggleMenu()"
        (menuClosed)="toggleMenu()"
    >
        <rmx-icon name="more-2-fill" class="mr-0 w-8"></rmx-icon>
    </button>
    <div class="p-4 flex items-center">
        <div class="pr-2.5 border-r border-gray-600 dark:border-white">
            <img
                class="w-16 h-16 rounded-md border border-gray-600 dark:border-white"
                [alt]="'Avatar'"
                [src]="$any(blog.author).profile.avatar"
                [routerLink]="['/profile', $any(blog.author)._id, $any(blog.author).userTag]"
            />
        </div>
        <div class="w-full pl-2.5">
            <h3 class="text-3xl font-medium">
                <a
                    [routerLink]="['/profile', $any(blog.author)._id, $any(blog.author).userTag, 'post', blog._id, blog.title | slugify]"
                    *ngIf="blog.audit.published === 'Published'"
                >
                    {{ blog.title }}
                </a>
                <a
                    [routerLink]="['/profile', $any(blog.author)._id, $any(blog.author).userTag, 'draft', blog._id]"
                    *ngIf="blog.audit.published === 'Unpublished'"
                >
                    {{ blog.title }}
                </a>
            </h3>
            <div class="flex items-center text-sm uppercase w-full">
                <div class="flex-1">
                    <ng-container *ngIf="blog.audit.publishedOn; else createdAt">
                        {{ blog.audit.publishedOn | localedate: 'fullDate' }}
                    </ng-container>
                    <ng-template #createdAt>
                        {{ blog.createdAt | localedate: 'fullDate' }}
                    </ng-template>
                </div>
                <div class="tag" [matTooltip]="'Views'" [matTooltipClass]="'offprint-tooltip'">
                    <rmx-icon name="bar-chart-box-line"></rmx-icon>
                    {{ blog.stats.views | abbreviate }}
                </div>
                <div class="separator">|</div>
                <div class="tag" [matTooltip]="'Comments'" [matTooltipClass]="'offprint-tooltip'">
                    <rmx-icon name="discuss-line"></rmx-icon>
                    {{ blog.stats.comments | abbreviate }}
                </div>
            </div>
        </div>
    </div>
    <div class="blog-body px-4 flex-1 line-clamp-6" [innerHTML]="blog.body | safeHtml"></div>
    <div class="flex flex-row items-center p-4">
        <div class="flex-1"></div>
        <div>
            <a
                class="text-sm flex items-center font-medium"
                *ngIf="blog.audit.published === 'Published'"
                [routerLink]="[
                        '/profile',
                        $any(blog.author)._id,
                        $any(blog.author).userTag | slugify,
                        'post',
                        blog._id,
                        blog.title | slugify,
                    ]">
                Continue Reading
                <rmx-icon name="arrow-right-s-line"></rmx-icon>
            </a>
            <a
                class="text-sm flex items-center font-medium"
                *ngIf="blog.audit.published === 'Unpublished'"
                [routerLink]="[
                        '/profile',
                        $any(blog.author)._id,
                        $any(blog.author).userTag | slugify,
                        'draft',
                        blog._id,
                    ]">
                Continue Reading
                <rmx-icon name="arrow-right-s-line"></rmx-icon>
            </a>
        </div>
    </div>
</div>

<mat-menu #editingMenu='matMenu' [xPosition]="'before'">
    <button mat-menu-item class="hover:scale-100" [routerLink]="['/profile', $any(blog.author)._id, $any(blog.author).userTag | slugify, 'draft', blog._id,]">
        <rmx-icon name="edit-line"></rmx-icon>
        <span>Edit blog</span>
    </button>
    <button mat-menu-item class="hover:scale-100" (click)="publishBlog()" *ngIf="blog.audit.published === 'Unpublished'">
        <rmx-icon name="check-line"></rmx-icon>
        <span>Publish</span>
    </button>
    <button mat-menu-item class="hover:scale-100" (click)="unpublishBlog()" *ngIf="blog.audit.published === 'Published'">
        <rmx-icon name="draft-line"></rmx-icon>
        <span>Convert to Draft</span>
    </button>
    <div class="w-full my-0.5 border-b border-gray-600 dark:border-white"></div>
    <button mat-menu-item class="hover:scale-100" (click)="deleteBlog()">
        <rmx-icon name="delete-bin-line"></rmx-icon>
        <span>Delete</span>
    </button>
</mat-menu>
