// libs/client/ui/src/lib/components/toggle/toggle.component.ts
import { Component } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
    selector: 'dragonfish-toggle',
    templateUrl: './toggle.component.html',
    styleUrls: ['./toggle.component.scss'],
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: ToggleComponent,
            multi: true,
        },
    ],
})
export class ToggleComponent implements ControlValueAccessor {
    value = false;
    onChange: (value: boolean) => void;

    toggleValue() {
        this.value = !this.value;
        this.onChange(this.value);
    }

    writeValue(value: boolean): void {
        this.value = value;
    }
    registerOnChange(fn: any): void {
        this.onChange = fn;
    }
    registerOnTouched(fn: any): void {
        // does nothing
    }
}

<div class="flex flex-row items-center mt-3 mb-3">
    <div class="switch-container w-12 h-6 flex items-center rounded-full" (click)="toggleValue()">
        <div
            class="switch w-4 h-4 rounded-full shadow-md transform duration-300 ease-in-out"
            [ngClass]="{ 'switch-activated': value }"
        ></div>
    </div>
    <label class="switch-label ml-3" for="toggle"><ng-content></ng-content></label>
</div>

// apps/client/src/lib/components/forms/Toggle.svelte
<script lang="ts">
  export let value = false;
</script>

<div class="flex flex-row items-center mt-3 mb-3 cursor-pointer" on:click={() => value = !value } tabindex="0">
  <div class="switch-container border border-zinc-300 dark:border-white w-12 h-6 flex items-center rounded-full" id='toggle'>
    <div
      class="switch w-4 h-4 rounded-full shadow-md transform duration-300 ease-in-out"
      class:switch-activated={value}
    ></div>
  </div>
  <label class="ml-3 select-none cursor-pointer text-sm" for="toggle"><slot /></label>
</div>

<style lang="scss">
  div.switch-container {
    background: transparent;
    padding: 0.2rem;
    cursor: pointer;
    div.switch {
      background: gray;
    }
    div.switch-activated {
      background: var(--accent);
      --tw-translate-x: 1.5rem/* 24px */;
    }
  }
</style>
