// libs/client/ui/src/lib/components/news-card/news-card.component.ts
import { Component, Input } from '@angular/core';
import { NewsCategory } from '@dragonfish/shared/models/content';

@Component({
    selector: 'dragonfish-news-card',
    templateUrl: './news-card.component.html',
    styleUrls: ['./news-card.component.scss'],
})
export class NewsCardComponent {
    @Input() post: any;

    categories = NewsCategory;
}

<div class="post p-2 shadow-lg rounded-md h-full">
    <div class="flex flex-1 items-center">
        <div class="mr-1.5">
            <img class="w-14 h-14 border border-gray-600 dark:border-white rounded-md" [src]="post.author.profile.avatar" [alt]="'avatar'">
        </div>
        <div class="flex-1 flex flex-col">
            <div class="relative top-1">
                <h4 class="text-xl font-medium">
                    <a [routerLink]="['/profile', post.author._id, post.author.userTag, 'post', post._id, post.title | slugify]">{{ post.title }}</a>
                </h4>
            </div>
            <div class="post-byline flex flex-row py-1 text-xs relative -top-1">
                <div>
                    by <a [routerLink]="['/profile', post.author._id, post.author.userTag]">
                    {{ $any(post.author).screenName }}
                </a>
                </div>
                <div class="mx-1">//</div>
                <div>
                    {{ post.audit.publishedOn | localedate: 'longDate' }}
                </div>
            </div>
        </div>
    </div>
    <div class="flex items-center">
        <div class="stat text-sm" [matTooltip]="'Views'" [matTooltipClass]="'offprint-tooltip'">
            <rmx-icon name="bar-chart-box-line"></rmx-icon>
            {{ post.stats.views }}
        </div>
        <div class="mx-1">|</div>
        <div class="stat text-sm" [matTooltip]="'Comments'" [matTooltipClass]="'offprint-tooltip'">
            <rmx-icon name="discuss-line"></rmx-icon>
            {{ post.stats.comments }}
        </div>
        <div class="flex-1"><!--spacer--></div>
        <div>
            <a
                class="continue-reading"
                [routerLink]="['/profile', post.author._id, post.author.userTag, 'post', post._id, post.title | slugify]"
            >
                Continue Reading
                <rmx-icon name="arrow-right-s-line"></rmx-icon>
            </a>
        </div>
    </div>
</div>

// apps/client/src/lib/components/ui/content/NewsCard.svelte
<script lang="ts">
    import { localeDate } from '$lib/util';
    import type { Blog } from '$lib/models/content/blogs';

    export let post: Blog;
</script>

<a
    class="w-full border border-zinc-600 dark:border-white rounded-md p-2 flex items-center mb-2 transition transform hover:scale-105 hover:bg-zinc-300 dark:hover:bg-zinc-700 cursor-pointer no-underline active:scale-100"
    href="/blog/{post._id}"
    style="color: var(--text-color);"
>
    <img
        src={post.author.profile.avatar}
        alt="demo avatar"
        class="rounded-full border-2"
        style="max-width: 2.5rem; border-color: var(--borders);"
    />
    <div class="truncate flex-1 w-full ml-2">
        <h4 class="text-lg font-medium top-1">
            {post.title}
        </h4>
        <div class="relative -top-1 flex items-center">
            <span class="text-xs">by {post.author.screenName}</span>
            <span class="text-xs mx-0.5">•</span>
            <span class="text-xs">{localeDate(post.audit.publishedOn, 'shortDate')}</span>
        </div>
    </div>
</a>
