// libs/client/ui/src/lib/components/tag-badge/tag-badge.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import { ContentKind, ContentRating, Genres, TagKind, WorkKind } from '@dragonfish/shared/models/content';

@Component({
    selector: 'dragonfish-tag-badge',
    templateUrl: './tag-badge.component.html',
    styleUrls: ['./tag-badge.component.scss'],
    encapsulation: ViewEncapsulation.None,
})
export class TagBadgeComponent {
    @Input() kind: TagKind;
    @Input() type: ContentKind;
    @Input() category: WorkKind;
    @Input() genre: Genres;
    @Input() rating: ContentRating;
    @Input() size: 'small' | 'medium' | 'large' = 'medium';
    @Input() hasIcon = true;

    types = ContentKind;
    categories = WorkKind;
    kinds = TagKind;
    genres = Genres;
    ratings = ContentRating;

    generateTooltip() {
        switch (this.kind) {
            case TagKind.Type: {
                if (this.type === ContentKind.ProseContent) {
                    return 'Prose';
                } else {
                    return 'Poetry';
                }
            }
            case TagKind.Category: {
                if (this.category === WorkKind.Original) {
                    return 'Original';
                } else {
                    return 'Fanwork';
                }
            }
            case TagKind.Genre: {
                switch (Genres[this.genre]) {
                    case Genres.Comedy:
                        return 'Comedy';
                    case Genres.Drama:
                        return 'Drama';
                    case Genres.Erotica:
                        return 'Erotica';
                    case Genres.Fantasy:
                        return 'Fantasy';
                    case Genres.Horror:
                        return 'Horror';
                    case Genres.Mystery:
                        return 'Mystery';
                    case Genres.Romance:
                        return 'Romance';
                    case Genres.Thriller:
                        return 'Thriller';
                    case Genres.Tragedy:
                        return 'Tragedy';
                    case Genres.ActionAdventure:
                        return 'Action/Adventure';
                    case Genres.ScienceFiction:
                        return 'Science Fiction';
                    case Genres.SliceOfLife:
                        return 'Slice of Life';
                    case Genres.SpeculativeFiction:
                        return 'Speculative Fiction';
                }
                break;
            }
            case TagKind.Rating: {
                if (this.rating === ContentRating.Everyone) {
                    return 'Everyone';
                } else if (this.rating === ContentRating.Teen) {
                    return 'Teen';
                } else if (this.rating === ContentRating.Mature) {
                    return 'Mature';
                } else if (this.rating === ContentRating.Explicit) {
                    return 'Explicit';
                }
            }
        }
    }
}

<div
    class="tag-pill"
    [ngClass]="{
        'fandom': kind === kinds.Fandom,
        'warning': kind === kinds.Warning,
        'category': kind === kinds.Category,
        'genre': kind === kinds.Genre,
        'type': kind === kinds.Type,
        'user': kind === kinds.User,
        'no-text': size === 'small',
        'big-text': size === 'large',
        'no-icon': !hasIcon,
        'everyone': rating === ratings.Everyone,
        'teen': rating === ratings.Teen,
        'mature': rating === ratings.Mature,
        'explicit': rating === ratings.Explicit
    }"
    [matTooltip]="generateTooltip()"
    [matTooltipDisabled]="size === 'large' || size === 'medium'"
    [matTooltipClass]="'offprint-tooltip'"
    [matTooltipShowDelay]="300"
>
    <ng-container *ngIf="kind === kinds.Type">
        <ng-container [ngSwitch]="type">
            <ng-container *ngSwitchCase="types.ProseContent">
                <rmx-icon name="book-open-line"></rmx-icon>
                <span class="tag-label">Prose</span>
            </ng-container>
            <ng-container *ngSwitchCase="types.PoetryContent">
                <rmx-icon name="quill-pen-line"></rmx-icon>
                <span class="tag-label">Poetry</span>
            </ng-container>
        </ng-container>
    </ng-container>
    <ng-container *ngIf="kind === kinds.Category">
        <ng-container [ngSwitch]="category">
            <ng-container *ngSwitchCase="categories.Original">
                <rmx-icon name="loader-2-line"></rmx-icon>
                <span class="tag-label">Original</span>
            </ng-container>
            <ng-container *ngSwitchCase="categories.Fanwork">
                <rmx-icon name="empathize-line"></rmx-icon>
                <span class="tag-label">Fanwork</span>
            </ng-container>
        </ng-container>
    </ng-container>
    <ng-container *ngIf="kind === kinds.Genre">
        <ng-container [ngSwitch]="genres[genre]">
            <ng-container *ngSwitchCase="genres.Comedy">
                <rmx-icon name="emotion-laugh-line"></rmx-icon>
                <span class="tag-label">Comedy</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Drama">
                <rmx-icon name="file-paper-2-line"></rmx-icon>
                <span class="tag-label">Drama</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Erotica">
                <rmx-icon name="door-closed-line"></rmx-icon>
                <span class="tag-label">Erotica</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Fantasy">
                <rmx-icon name="magic-line"></rmx-icon>
                <span class="tag-label">Fantasy</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Horror">
                <rmx-icon name="ghost-2-line"></rmx-icon>
                <span class="tag-label">Horror</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Mystery">
                <rmx-icon name="search-eye-line"></rmx-icon>
                <span class="tag-label">Mystery</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Romance">
                <rmx-icon name="hearts-line"></rmx-icon>
                <span class="tag-label">Romance</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.ScienceFiction">
                <rmx-icon name="aliens-line"></rmx-icon>
                <span class="tag-label">Science Fiction</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.SliceOfLife">
                <rmx-icon name="home-3-line"></rmx-icon>
                <span class="tag-label">Slice of Life</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.SpeculativeFiction">
                <rmx-icon name="meteor-line"></rmx-icon>
                <span class="tag-label">Speculative Fiction</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Thriller">
                <rmx-icon name="spy-line"></rmx-icon>
                <span class="tag-label">Thriller</span>
            </ng-container>
            <ng-container *ngSwitchCase="genres.Tragedy">
                <rmx-icon name="skull-line"></rmx-icon>
                <span class="tag-label">Tragedy</span>
            </ng-container>
            <ng-container *ngSwitchDefault>
                <rmx-icon name="sword-line"></rmx-icon>
                <span class="tag-label">Action/Adventure</span>
            </ng-container>
        </ng-container>
    </ng-container>
    <ng-container *ngIf="kind === kinds.Rating">
        <ng-container [ngSwitch]="rating">
            <ng-container *ngSwitchCase="ratings.Everyone">
                <span class="tag-label">Everyone</span>
                <span class="rating-label-small">E</span>
            </ng-container>
            <ng-container *ngSwitchCase="ratings.Teen">
                <span class="tag-label">Teen</span>
                <span class="rating-label-small">T</span>
            </ng-container>
            <ng-container *ngSwitchCase="ratings.Mature">
                <span class="tag-label">Mature</span>
                <span class="rating-label-small">M</span>
            </ng-container>
            <ng-container *ngSwitchCase="ratings.Explicit">
                <span class="tag-label">Explicit</span>
                <span class="rating-label-small">X</span>
            </ng-container>
        </ng-container>
    </ng-container>
</div>

// apps/client/src/lib/components/ui/content/TagBadge.svelte
<script lang="ts">
    import { Genres, TagKind, TagsModel, WorkKind } from '$lib/models/content/works';
    import { ContentKind, ContentRating } from '$lib/models/content';
    import {
        BookOpenLine,
        QuillPenLine,
        EmpathizeLine,
        Loader2Line,
        EmotionLaughLine,
        FilePaper2Line,
        DoorClosedLine,
        MagicLine,
        Ghost2Line,
        SearchEyeLine,
        HeartsLine,
        AliensLine,
        Home3Line,
        MeteorLine,
        SpyLine,
        SkullLine,
        SwordLine,
    } from 'svelte-remixicon';
    import { slugify } from '$lib/util';
    import { formatTagName } from '$lib/util/format-tag-name';

    export let size: 'small' | 'medium' | 'large' = 'medium';
    export let hasIcon = true;
    export let kind: TagKind;
    export let type: ContentKind = null;
    export let category: WorkKind = null;
    export let genre: Genres = null;
    export let rating: ContentRating = null;
    export let tag: TagsModel = null;
</script>

<div
    class="tag-pill"
    class:fandom={kind === TagKind.Fandom}
    class:warning={kind === TagKind.Warning}
    class:category={kind === TagKind.Category}
    class:genre={kind === TagKind.Genre}
    class:type={kind === TagKind.Type}
    class:user={kind === TagKind.User}
    class:no-text={size === 'small'}
    class:big-text={size === 'large'}
    class:no-icon={!hasIcon}
    class:everyone={rating === ContentRating.Everyone}
    class:teen={rating === ContentRating.Teen}
    class:mature={rating === ContentRating.Mature}
    class:explicit={rating === ContentRating.Explicit}
>
    {#if kind === TagKind.Type}
        {#if type === ContentKind.ProseContent}
            <BookOpenLine />
            <span class="tag-label">Prose</span>
        {:else if type === ContentKind.PoetryContent}
            <QuillPenLine />
            <span class="tag-label">Poetry</span>
        {/if}
    {:else if kind === TagKind.Category}
        {#if category === WorkKind.Fanwork}
            <EmpathizeLine />
            <span class="tag-label">Fanwork</span>
        {:else if category === WorkKind.Original}
            <Loader2Line />
            <span class="tag-label">Original</span>
        {/if}
    {:else if kind === TagKind.Genre}
        {#if genre === Genres.Comedy}
            <EmotionLaughLine />
            <span class="tag-label">Comedy</span>
        {:else if genre === Genres.Drama}
            <FilePaper2Line />
            <span class="tag-label">Drama</span>
        {:else if genre === Genres.Erotica}
            <DoorClosedLine />
            <span class="tag-label">Erotica</span>
        {:else if genre === Genres.Fantasy}
            <MagicLine />
            <span class="tag-label">Fantasy</span>
        {:else if genre === Genres.Horror}
            <Ghost2Line />
            <span class="tag-label">Horror</span>
        {:else if genre === Genres.Mystery}
            <SearchEyeLine />
            <span class="tag-label">Mystery</span>
        {:else if genre === Genres.Romance}
            <HeartsLine />
            <span class="tag-label">Romance</span>
        {:else if Genres[genre] === Genres.ScienceFiction}
            <AliensLine />
            <span class="tag-label">Science Fiction</span>
        {:else if Genres[genre] === Genres.SliceOfLife}
            <Home3Line />
            <span class="tag-label">Slice of Life</span>
        {:else if Genres[genre] === Genres.SpeculativeFiction}
            <MeteorLine />
            <span class="tag-label">Speculative Fiction</span>
        {:else if genre === Genres.Thriller}
            <SpyLine />
            <span class="tag-label">Thriller</span>
        {:else if genre === Genres.Tragedy}
            <SkullLine />
            <span class="tag-label">Tragedy</span>
        {:else if Genres[genre] === Genres.ActionAdventure}
            <SwordLine />
            <span class="tag-label">Action/Adventure</span>
        {/if}
    {:else if kind === TagKind.Rating}
        {#if rating === ContentRating.Everyone}
            <span class="tag-label">Everyone</span>
            <span class="rating-label-small">E</span>
        {:else if rating === ContentRating.Teen}
            <span class="tag-label">Teen</span>
            <span class="rating-label-small">T</span>
        {:else if rating === ContentRating.Mature}
            <span class="tag-label">Mature</span>
            <span class="rating-label-small">M</span>
        {:else if rating === ContentRating.Explicit}
            <span class="tag-label">Explicit</span>
            <span class="rating-label-small">X</span>
        {/if}
    {:else if kind === TagKind.Fandom && tag !== null}
        <span class="tag-label">
            <a href="/tag/{tag._id}/{slugify(tag.name)}">
                {formatTagName(tag)}
            </a>
        </span>
    {/if}
</div>

<style lang="scss">
    div.tag-pill {
        @apply px-1 py-0.5 flex items-center rounded-md mx-0.5 mt-1 text-white transition transform cursor-pointer h-[1.75rem];
        :global(svg) {
            @apply w-4 relative mr-1;
        }

        span.tag-label {
            @apply text-sm;
            a {
                @apply font-light text-white;
            }
        }

        span.rating-label-small {
            @apply hidden text-sm font-medium;
        }

        &.no-text {
            @apply px-1.5;
            :global(svg) {
                @apply mr-0;
            }

            span.tag-label {
                @apply hidden;
            }

            &.no-icon {
                @apply px-2 py-0.5;
                span.rating-label-small {
                    @apply block;
                }
            }
        }

        &.big-text {
            :global(svg) {
                @apply w-6 mr-0.5;
            }

            span.tag-label {
                @apply text-sm mr-1;
            }
        }

        &:hover {
            @apply scale-105;
        }

        &:active {
            @apply scale-100;
        }

        &.fandom {
            @apply bg-gray-500 hover:bg-gray-600;
        }

        &.warning {
        }

        &.category {
            @apply bg-purple-600 hover:bg-purple-800;
        }

        &.genre {
            @apply bg-green-600 hover:bg-green-800;
        }

        &.type {
            @apply bg-indigo-600 hover:bg-indigo-800;
        }

        &.user {
        }

        &.everyone {
            @apply bg-green-700 hover:bg-green-900;
        }

        &.teen {
            @apply bg-yellow-400 hover:bg-yellow-600;
        }

        &.mature {
            @apply bg-yellow-700 hover:bg-yellow-900;
        }

        &.explicit {
            @apply bg-red-700 hover:bg-red-900;
        }

        &.no-icon {
            @apply py-1;
        }
    }
</style>
