// apps/client/src/lib/components/ui/user/LogInForm.svelte
<script lang="ts">
    import { createEventDispatcher } from 'svelte';
    import { createForm } from 'felte';
    import { LoginCircleLine } from 'svelte-remixicon';
    import TextField from '$lib/components/forms/TextField.svelte';
    import Button from '$lib/components/ui/misc/Button.svelte';
    import Toggle from '$lib/components/forms/Toggle.svelte';
    import { login } from '$lib/repo/session.repo';
    import type { LoginForm } from '$lib/models/accounts/forms';

    let submitting = false;
    const dispatch = createEventDispatcher();

    const { form, data, errors } = createForm({
        onSubmit: async (values) => {
            submitting = true;

            const formInfo: LoginForm = {
                email: values.email,
                password: values.password,
                rememberMe: values.rememberMe,
            };

            await login(formInfo).then(() => {
                submitting = false;
                dispatch('login');
            });
        },
        validate: (values) => {
            const errors = {
                email: '',
                password: '',
            };
            if (!values.email || !/^[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+/.test(values.email)) {
                errors.email = 'Not a valid email address.';
            }
            if (!values.password) {
                errors.password = `Aren't you forgetting something?`;
            }
            return errors;
        },
        onError: () => {
            submitting = false;
        },
    });
</script>

<form class="flex flex-col" use:form>
    <TextField
        name="email"
        type="email"
        title="Email address"
        placeholder="somebody@example.net"
        errorMessage={$errors.email}
    />
    <TextField
        name="password"
        type="password"
        title="Password"
        placeholder="••••••••••"
        errorMessage={$errors.password}
    />
    <div class="my-1">
        <a href="/" class="text-sm">Forgot your password?</a>
    </div>
    <div class="flex items-center">
        <Toggle bind:value={$data.rememberMe}>Remember me</Toggle>
        <div class="flex-1" />
        <Button type="submit" loading={submitting} loadingText="Signing in...">
            <LoginCircleLine class="button-icon" />
            <span class="button-text">Log In</span>
        </Button>
    </div>
</form>

// libs/client/ui/src/lib/components/auth/login-form/login-form.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '@dragonfish/client/repository/session/services';
import { AlertsService } from '@dragonfish/client/alerts';
import { LoginModel } from '@dragonfish/shared/models/accounts';

@Component({
    selector: 'dragonfish-login-form',
    templateUrl: './login-form.component.html',
})
export class LoginFormComponent {
    @Output() isSuccess = new EventEmitter<LoginModel>();

    loginForm = new FormGroup({
        email: new FormControl('', [Validators.required, Validators.email]),
        password: new FormControl('', [Validators.required]),
        rememberMe: new FormControl(false),
    });

    constructor(private auth: AuthService, private alerts: AlertsService) {}

    get fields() {
        return this.loginForm.controls;
    }

    submitForm() {
        if (this.fields.email.invalid) {
            this.alerts.error(`You need to provide a valid email address.`);
            return;
        }

        if (this.fields.password.invalid) {
            this.alerts.error(`You need to provide your password.`);
            return;
        }

        const info: LoginModel = {
            email: this.fields.email.value,
            password: this.fields.password.value,
            rememberMe: this.fields.rememberMe.value,
        };

        this.isSuccess.emit(info);
    }
}

<form [formGroup]="loginForm" (ngSubmit)="submitForm()">
    <dragonfish-text-field
        [formControlName]="'email'"
        [name]="'email'"
        [type]="'email'"
        [label]="'Email Address'"
        [placeholder]="'someone@example.com'"
    ></dragonfish-text-field>

    <dragonfish-text-field
        [formControlName]="'password'"
        [name]="'password'"
        [type]="'password'"
        [label]="'Password'"
        [placeholder]="'••••••••••'"
    ></dragonfish-text-field>

    <hr />

    <div class="flex flex-row items-center mt-5">
        <div class="flex-1">
            <dragonfish-toggle [formControlName]="'rememberMe'">
                Remember Me For 30 Days
            </dragonfish-toggle>
        </div>
        <div>
            <button type="submit"><rmx-icon name="login-circle-line"></rmx-icon>Log In</button>
        </div>
    </div>
</form>
