// apps/client/src/lib/components/ui/user/RegisterForm.svelte
<script lang="ts">
    // TODO: verify that the registration form works correctly

    import { createEventDispatcher } from 'svelte';
    import { createForm } from 'felte';
    import { UserAddLine } from 'svelte-remixicon';
    import TextField from '$lib/components/forms/TextField.svelte';
    import Button from '$lib/components/ui/misc/Button.svelte';
    import Toggle from '$lib/components/forms/Toggle.svelte';
    import { register } from '$lib/repo/session.repo';
    import type { RegisterForm } from '$lib/models/accounts/forms';

    let submitting = false;
    const dispatch = createEventDispatcher();

    const { form, data, errors } = createForm({
        onSubmit: async (values) => {
            submitting = true;
            const formInfo: RegisterForm = {
                email: values.email,
                password: values.password,
                inviteCode: values.inviteCode,
                termsAgree: values.termsAgree,
            };

            await register(formInfo).then(() => {
                submitting = false;
                dispatch('register');
            });
        },
        validate: (values) => {
            const errors = {
                email: '',
                password: '',
                repeatPassword: '',
                inviteCode: '',
                ageCheck: '',
                termsAgree: '',
            };
            if (!values.email || !/^[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+/.test(values.email)) {
                errors.email = `That's not a valid email address.`;
            }
            if (!values.password) {
                errors.password = `Aren't you forgetting something?`;
            }
            if (values.password && values.password.length < 8) {
                errors.password = `Passwords must be at least 8 characters long.`;
            }
            if (!values.repeatPassword || values.password !== values.repeatPassword) {
                errors.repeatPassword = `Passwords must match.`;
            }
            if (!values.inviteCode) {
                errors.inviteCode = `You must provide an invite code.`;
            }
            if (values.ageCheck === false) {
                errors.ageCheck = `You must be at least 13 years or older to join.`;
            }
            if (values.termsAgree === false) {
                errors.termsAgree = `You must agree in order to join.`;
            }
            return errors;
        },
        onError: () => {
            submitting = false;
        },
    });
</script>

<form class="flex flex-col" use:form>
    <TextField
        name="email"
        type="email"
        title="Email address"
        placeholder="somebody@example.net"
        errorMessage={$errors.email}
    />
    <TextField
        name="password"
        type="password"
        title="Password"
        placeholder="••••••••••"
        errorMessage={$errors.password}
    />
    <TextField
        name="repeatPassword"
        type="password"
        title="Repeat Password"
        placeholder="••••••••••"
        errorMessage={$errors.repeatPassword}
    />
    <TextField
        name="inviteCode"
        type="text"
        title="Invite Code"
        placeholder="myInviteCode"
        errorMessage={$errors.inviteCode}
    />
    <div class="my-0.5" />
    <Toggle bind:value={$data.ageCheck}>I am 13 years of age or older.</Toggle>
    <Toggle bind:value={$data.termsAgree}>
        I agree to the Terms & Conditions, Privacy Policy, and Code of Conduct.
    </Toggle>
    <div class="flex items-center">
        <div class="flex-1" />
        <Button type="submit" loading={submitting} loadingText="Signing up...">
            <UserAddLine class="button-icon" />
            <span class="button-text">Sign up</span>
        </Button>
    </div>
</form>

// libs/client/ui/src/lib/components/auth/register-form/register-form.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '@dragonfish/client/repository/session/services';
import { AccountForm } from '@dragonfish/shared/models/accounts';

@Component({
    selector: 'dragonfish-register-form',
    templateUrl: './register-form.component.html',
})
export class RegisterFormComponent {
    @Output() isSuccess = new EventEmitter<AccountForm>();

    registerForm = new FormGroup({
        email: new FormControl('', [Validators.required, Validators.email]),
        password: new FormControl('', [Validators.required, Validators.minLength(8)]),
        repeatPassword: new FormControl('', [Validators.required, Validators.minLength(8)]),
        inviteCode: new FormControl('', [Validators.required]),
        termsAgree: new FormControl(false, [Validators.requiredTrue]),
        isMinAge: new FormControl(false, [Validators.requiredTrue]),
    });

    constructor(private auth: AuthService) {}

    get fields() {
        return this.registerForm.controls;
    }

    submitForm() {
        if (this.registerForm.invalid) {
            alert(`Check the info you've entered, because it doesn't look right to us.`);
            return;
        }

        if (this.fields.password.value !== this.fields.repeatPassword.value) {
            alert(`Your passwords don't match.`);
            return;
        }

        const info: AccountForm = {
            email: this.fields.email.value,
            password: this.fields.password.value,
            inviteCode: this.fields.inviteCode.value,
            termsAgree: this.fields.termsAgree.value,
        };

        this.isSuccess.emit(info);
    }
}

<form [formGroup]="registerForm" (ngSubmit)="submitForm()">
    <dragonfish-text-field
        [formControlName]="'email'"
        [name]="'email'"
        [type]="'email'"
        [label]="'Email Address'"
        [placeholder]="'someone@example.com'"
    ></dragonfish-text-field>

    <dragonfish-text-field
        [formControlName]="'password'"
        [name]="'password'"
        [type]="'password'"
        [label]="'Password'"
        [placeholder]="'••••••••••'"
    ></dragonfish-text-field>

    <dragonfish-text-field
        [formControlName]="'repeatPassword'"
        [name]="'repeatPassword'"
        [type]="'password'"
        [label]="'Repeat Password'"
        [placeholder]="'••••••••••'"
    ></dragonfish-text-field>

    <dragonfish-text-field
        [formControlName]="'inviteCode'"
        [name]="'inviteCode'"
        [type]="'text'"
        [label]="'Invite Code'"
        [placeholder]="'myInviteCode'"
    ></dragonfish-text-field>

    <hr />

    <dragonfish-toggle [formControlName]="'termsAgree'">
        I agree to the Terms of Service,<br/>Privacy Policy, and Code of Conduct.
    </dragonfish-toggle>
    <dragonfish-toggle [formControlName]="'isMinAge'">
        I am at least thirteen years old.
    </dragonfish-toggle>

    <div class="flex flex-row justify-end">
        <button type="submit"><rmx-icon name="user-add-line"></rmx-icon>Register</button>
    </div>
</form>
